PROJECT = epuck_driver

GLOBAL_PATH = ../e-puck2_main-processor

CSRC += ./main.c \
		$(wildcard modules/src/*.c)

INCDIR += -Imodules/include -I.

#Jump to the main Makefile
include $(GLOBAL_PATH)/Makefile