
PROJECT = TOF_Logging

GLOBAL_PATH = ../e-puck2_main-processor

CSRC += ./main.c \
		$(wildcard modules/src/*.c)

INCDIR += modules/include

#Jump to the main Makefile
include $(GLOBAL_PATH)/Makefile